# Generated by Django 4.1.3 on 2022-11-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_alumnos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
