# Generated by Django 4.1.3 on 2022-11-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_delete_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='nacimiento',
        ),
    ]
