# Generated by Django 4.1.3 on 2022-11-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0004_remove_alumnos_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='comision',
        ),
    ]
